# Generated by Django 4.1.5 on 2023-01-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_numbar',
            new_name='phone_number',
        ),
    ]
