# Generated by Django 4.1.5 on 2023-03-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_email'),
        ('Landing_page', '0002_product_product_price_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=6)),
                ('kg', models.CharField(max_length=1)),
                ('delivery_charge', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Customer.customer')),
            ],
        ),
    ]
