# Generated by Django 4.1.5 on 2023-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kg',
            field=models.PositiveIntegerField(),
        ),
    ]
